version: "3.3"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    volumes:
      - ./:/app
      - static:/static
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - .:/app
      - ./static/:/static
    restart: on-failure
    depends_on:
      - web

  db:
    image: postgres:12-alpine
    networks:
      - default
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${SQL_USER}
      - POSTGRES_PASSWORD=${SQL_PASSWORD}
      - POSTGRES_DB=${SQL_DATABASE}

  redis:
      image: redis:latest
      restart: always
      environment:
        - REDIS_HOST=redis
      volumes:
        - redis_data:/data

volumes:
  postgres_data:
  redis_data:
  static: