# Generated by Django 3.2.6 on 2021-09-14 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_reminder_notified',
            field=models.BooleanField(default=False),
        ),
    ]
