# Generated by Django 3.2.6 on 2021-08-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='foundation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='create_date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата выхода игры'),
        ),
    ]
