# Generated by Django 3.2.6 on 2021-08-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamecategory',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
