# Generated by Django 3.2.6 on 2021-08-08 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210808_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creator',
            name='foundation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
